project_id = "mvhxyqwicmvnshmqkdan"

[functions.ai-copilot]
verify_jwt = true

[functions.tiktok-auth]
verify_jwt = true

[functions.tiktok-metrics]
verify_jwt = true

[functions.tiktok-post]
verify_jwt = true

[functions.tiktok-shop]
verify_jwt = true
